name: Merge dependabot pr
on:
  workflow_call:

jobs:
  merge-pullrequests:
    runs-on: ubuntu-latest
    steps:
      - run: echo "prnumber=$(gh pr list --repo $GITHUB_REPOSITORY --search "status:success label:automerge" -A app/dependabot -L 1 --json number --template '{{range .}}{{printf "%.0f\n" .number}}{{end}}')" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ github.token }}
      - run: gh pr merge ${{ env.prnumber }} --squash --repo $GITHUB_REPOSITORY
        if: "${{ env.prnumber != '' }}"
        env:
          GH_TOKEN: ${{ github.token }}
      - run: gh workflow run workflow.yml --repo $GITHUB_REPOSITORY
        if: "${{ env.prnumber != '' }}"
        env:
          GH_TOKEN: ${{ github.token }}
