name: Merge dependabot pr
on:
  workflow_call:

jobs:
  merge-pullrequests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const today = new Date();
            const julStart = new Date(today.getFullYear(), 11, 20);
            const julSlutt = new Date(today.getFullYear(), 11, 31);
            const nyttaarStart = new Date(today.getFullYear(), 0, 1);
            const nyttaarSlutt = new Date(today.getFullYear(), 0, 3);

            if ((today >= julStart && today <= julSlutt) || (today >= nyttaarStart && today <= nyttaarSlutt)) {
                console.log('Skriptet kjører ikke i jula');
                return;
            }


            const pulls = await github.request('GET /repos/{owner}/{repo}/pulls', {
                owner: context.repo.owner,
                repo: context.repo.repo,
            })

            const filtrert = pulls.data
                .filter((it) => it.state == 'open')
                .filter((it) => !it.head.repo.fork)
                .filter((it) => it.labels.some((l) => l.name == 'automerge'))
                .filter((it) => {
                    const prCreated = new Date(it.created_at)
                    if (it.title.includes('navikt') || it.title.includes('aksel')) {
                      const twoDays = 2 * 24 * 60 * 60 * 1000
                      return prCreated.getTime() < Date.now() - twoDays
                    }
                    const oneWeek = 7 * 24 * 60 * 60 * 1000
                    return prCreated.getTime() < Date.now() - oneWeek
                })
                .map((it) => {
                    return {
                        title: it.title,
                        number: it.number,

                    }
                })
                .map(async (it) => {
                    const QUERY = `query($owner: String!, $repo: String!, $pull_number: Int!) {
                                          repository(owner: $owner, name:$repo) {
                                            pullRequest(number:$pull_number) {
                                              commits(last: 1) {
                                                nodes {
                                                  commit {
                                                    statusCheckRollup {
                                                      state
                                                    }
                                                  }
                                                }
                                              }
                                            }
                                          }
                                        }`

                    const result = await github.graphql(QUERY, {
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        pull_number: it.number,
                    })
                    const [{ commit: lastCommit }] =
                        result.repository.pullRequest.commits.nodes

                    return {
                        title: it.title,
                        number: it.number,
                        checksOk: lastCommit.statusCheckRollup?.state === 'SUCCESS',
                    }
                })

            const allePrs = await Promise.all(filtrert)
            const mergeablePromise = allePrs
                .filter((it) => it.checksOk)
                .map(async (it) => {
                    const prdata = await github.request('GET /repos/{owner}/{repo}/pulls/{pull_number}', {
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        pull_number: it.number
                    })
                    return {
                        title: it.title,
                        number: it.number,
                        mergeable: prdata.data.mergeable
                    }
                })


            const mergeable = (await Promise.all(mergeablePromise))
                .filter((it) => {
                  return it.mergeable;
                })
            if (mergeable.length > 0) {
                const pr = mergeable[0]
                console.log('Merger PR', pr.title)
                await github.request('PUT /repos/{owner}/{repo}/pulls/{pull_number}/merge', {
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    pull_number: pr.number,
                    merge_method: 'squash'
                })
                console.log('Starter main workflow')

                await github.request(
                    'POST /repos/{owner}/{repo}/actions/workflows/{workflow_id}/dispatches',
                    {
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        workflow_id: 'workflow.yml',
                        ref: 'main',
                    }
                )
            } else {
                console.log('Ingen PRer å merge')
            }
