name: Nais deploy dev og prod
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      app:
        required: true
        type: string
      nais-template:
        required: false
        default: nais/app/naiserator.yaml
        type: string
      prod-vars:
        required: false
        default: nais/app/prod.yaml
        type: string
      dev-vars:
        required: false
        default: nais/app/dev.yaml
        type: string
      dev-only:
        required: false
        default: false
        type: string
jobs:
  deploy-til-dev:
    if: github.ref_name == 'master' || startsWith(github.ref_name, 'dev-')
    name: Deploy til dev
    timeout-minutes: 15
    runs-on: ubuntu-latest
    concurrency: deploy-${{ inputs.app }}-til-dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        name: Deploy til dev
        env:
          CLUSTER: dev-gcp
          IMAGE: ${{ inputs.image }}
          RESOURCE: ${{ inputs.nais-template }}
          VARS: ${{ inputs.dev-vars }}

  deploy-til-prod:
    if: ${{ github.ref_name == 'master' &&  inputs.dev-only  == 'false' }}
    name: Deploy til prod
    timeout-minutes: 15
    runs-on: ubuntu-latest
    concurrency: deploy-${{ inputs.app }}-til-prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: nais/deploy/actions/deploy@v2
        name: Deploy til prod
        env:
          IMAGE: ${{ inputs.image }}
          CLUSTER: prod-gcp
          RESOURCE: ${{ inputs.nais-template }}
          VARS: ${{ inputs.prod-vars }}
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@b24d75fe0e728a4bf9fc42ee217caa686d141ee8
        if: failure() && github.ref_name == 'master'
        env:
          SLACK_COLOR: '#ff0000'
          SLACK_MESSAGE: ${{ inputs.app }} deploy til produksjon feilet
          SLACK_TITLE: ':sad_cowboy:'
          SLACK_WEBHOOK: ${{ secrets.SPOKELSER_WEBHOOK }}
