name: Nais deploy dev og prod
on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      app:
        required: true
        type: string

jobs:
  deploy-til-dev-gcp:
    if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/heads/dev-')
    name: Deploy til dev-gcp
    runs-on: ubuntu-latest
    concurrency: deploy-til-dev-gcp
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        name: Deploy til dev-gcp
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          IMAGE: ${{ inputs.image }}
          RESOURCE: nais/app/naiserator.yaml
          VARS: nais/app/dev.yaml

  deploy-til-prod-gcp:
    if: github.ref == 'refs/heads/master'
    name: Deploy til prod-gcp
    runs-on: ubuntu-latest
    concurrency: deploy-til-prod-gcp
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        name: Deploy til prod-gcp
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          IMAGE: ${{ inputs.image }}
          CLUSTER: prod-gcp
          RESOURCE: nais/app/naiserator.yaml
          VARS: nais/app/prod.yaml
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@12e36fc18b0689399306c2e0b3e0f2978b7f1ee7
        if: failure() && github.ref == 'refs/heads/master'
        env:
          SLACK_COLOR: '#ff0000'
          SLACK_MESSAGE: ${{ inputs.app }} deploy til produksjon feilet
          SLACK_TITLE: ':sad_cowboy:'
          SLACK_WEBHOOK: ${{ secrets.SPOKELSER_WEBHOOK }}
